### ISSUE TITLE
The checkbox column does show for me TBird OS X.

### ISSUE THREAD

**Issue by PReinie** [mganss/CheckboxColumn#4]
I installed and enabled the add-in for Thunderbird 60.3.3 (64-bit) on Mac OS X 10.11.6 but the columns do not show up.

I have enabled and restarted TBird and disabled and restarted then re-enabled with restart, including restart of the MacBook and still no check-box column.

Any ideas at what to look at?

**Comment by mganss** [comment]
You need to add the column by clicking on the rightmost icon in the header row (above the scrollbar) and then selecting the "Selected" column. Here's more: https://support.mozilla.org/en-US/kb/message-list-columns

**Comment by PReinie** [comment]
Thank you for the quick response and perfect instructions. That worked.

It's interesting that when first added-in and after restarting TBird, it sets the "largeFont" mode to on/true, but doesn't enable/set the "Selected" column to be on (checked).

Great add-in, thanks!
