### ISSUE TITLE
Add an option to remove the select-all checkbox

### ISSUE THREAD

**Issue by lameventanas** [mganss/CheckboxColumn#5]
Hi there,

I find this addon very useful for my parents, as they are used to using email through web interfaces, they don't like to use Control or Shift to select multiple messages.

However, as old people are not so adept with computers, they make mistakes.  And they have already used the select-all checkbox (in the column header) and deleted all their emails by mistake.

Can you please add an option to remove that select-all checkbox in the column header?

Also, square checkboxes instead of circles would look more in line with the rest of Thunderbird.

Thanks!

**Comment by mganss** [comment]
Good idea. We have options already so this should be easy.

**Comment by mganss** [comment]
Added in 1.3.0.
